Detail_mssg={'The word “radar” is an acronym for “radio detection and ranging.” A radar measures the distance, or range, to an object by transmitting an electromagnetic signal to and receiving an echo reflected from the object. Radars provide their own signals to detect the presence of objects. Therefore, radars are known as active, remote-sensing instruments. Because radars provide their own signal, they can operate during day or night. In addition, radar signals typically penetrate clouds and rain, which means that radar images can be acquired not only during day or night but also under (almost) all weather conditions. For these reasons, radars are often referred to as all-weather instruments. Imaging, remote-sensing radars, such as SAR, produce high-resolution (from submeter to a few tens of meters) images of surfaces. The geophysical information can be derived from these high-resolution images by using proper postprocessing techniques.'
'This project focuses on a specific class of implementation of synthetic aperture radar with particular emphasis on the use of polarization to infer the geophysical properties of the scene. As mentioned above, SAR is a way to achieve high-resolution images using radio waves. This design is based on Artificial Neural Network with Fuzzy classifier using Matlab to classify the region as given below.'
'1.	Urban'
'2.	Vegetation'
'3.	Water '};
hd=figure('MenuBar','none','Position',[500.3333  100.0000  614.4000  256.000+70], 'Name', 'Basic Information about this design');

hDsp = uicontrol(hd,'Style','text',...
		'String',Detail_mssg,...
		'HorizontalAlignment','left',...
		'BackgroundColor','white',...
		'FontSize',10,...
              'Position',[5  30 607 290]);

CloseB = uicontrol('Style', 'pushbutton', 'String', 'OK',...
    'Position', [570 5 40 20], 'Callback', 'close');
